TRADUCCION_GENEROS = {
    # --- CINE, SERIES Y MULTIMEDIA GENERAL (TMDB) ---
    "Action": "Acción",
    "Adventure": "Aventura",
    "Animation": "Animación",
    "Comedy": "Comedia",
    "Crime": "Crimen",
    "Documentary": "Documental",
    "Drama": "Drama",
    "Family": "Familia",
    "Fantasy": "Fantasía",
    "History": "Historia",
    "Horror": "Terror",
    "Music": "Música",
    "Mystery": "Misterio",
    "Romance": "Romance",
    "Sci-Fi": "Ciencia ficción",
    "Science Fiction": "Ciencia ficción",
    "TV Movie": "Película de TV",
    "Thriller": "Suspenso",
    "War": "Guerra",
    "Western": "Western",

    # --- ANIME Y MANGA (AniList / Tags específicos) ---
    "Ecchi": "Ecchi",
    "Hentai": "Hentai",
    "Mecha": "Mecha",
    "Slice of Life": "Recuentos de la vida",
    "Supernatural": "Sobrenatural",
    "Psychological": "Psicológico",
    "Mahou Shoujo": "Magical Girl",
    "Sports": "Deportes",
    "School": "Escolar",
    "Gourmet": "Cocina",
    "Idol": "Idols",
    "Space": "Espacio",
    "Isekai": "Isekai",
    "Cyberpunk": "Cyberpunk",
    "Post-Apocalyptic": "Post-Apocalíptico",

    # --- VIDEOJUEGOS (RAWG / Etiquetas de Gameplay) ---
    "Shooter": "Disparos (Shooter)",
    "RPG": "Rol (RPG)",
    "Strategy": "Estrategia",
    "Puzzle": "Puzles",
    "Arcade": "Arcade",
    "Platformer": "Plataformas",
    "Racing": "Carreras",
    "Massively Multiplayer": "Multijugador masivo",
    "Fighting": "Lucha",
    "Simulation": "Simulación",
    "Indie": "Independiente",
    "Card Game": "Juego de cartas",
    "Casual": "Casual",
    "Educational": "Educativo",
    "Open World": "Mundo abierto",
    "Survival": "Supervivencia",

    # --- LIBROS Y LITERATURA (Hardcover / Google Books) ---
    "Fiction": "Ficción",
    "Non-Fiction": "No ficción",
    "Juvenile Fiction": "Ficción juvenil",
    "Young Adult": "Juvenil (YA)",
    "Young Adult Fiction": "Ficción juvenil adulta",
    "Literary Criticism": "Crítica literaria",
    "Biography": "Biografía",
    "Autobiography": "Autobiografía",
    "Philosophy": "Filosofía",
    "Classics": "Clásicos",
    "Self-Help": "Autoayuda",
    "Poetry": "Poesía",
    "Contemporary": "Contemporáneo",
    "Historical Fiction": "Ficción histórica",
    "Essays": "Ensayos",

    # --- TEMÁTICAS, SUBGÉNEROS Y TAGS "MISC" (Para tu uso personal) ---
    "Urban Fantasy": "Fantasía urbana",
    "Dark Fantasy": "Fantasía oscura",
    "Dystopian": "Distopía",
    "Steampunk": "Steampunk",
    "High Fantasy": "Alta fantasía",
    "Spicy": "Spicy / Hot",
    "Erotica": "Erótica",
    "Angels": "Ángeles",
    "Demons": "Demonios",
    "Vampires": "Vampiros",
    "Zombies": "Zombis",
    "Spirituality": "Espiritualidad",
    "Magic": "Magia",
    "Mythology": "Mitología",
    "Detective": "Detectivesco",
    "Noir": "Noir / Cine negro",
    "Politics": "Política",
    "Health & Fitness": "Salud y Bienestar",
    "Travel": "Viajes"
}
def display_genre():  
    return {g for g in TRADUCCION_GENEROS.values()}

def traducir_generos(lista):
    return [TRADUCCION_GENEROS.get(g, g) for g in lista]